'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),pub=path.join(root,'public');
const DEBUG=9337;let checks=0;const failures=[];
const ok=(v,m)=>{checks++;if(!v)failures.push(m)};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitJson(url,timeout=10000){const end=Date.now()+timeout;while(Date.now()<end){try{const r=await fetch(url);if(r.ok)return await r.json()}catch{}await sleep(100)}throw new Error('Timed out waiting for '+url)}
class CDP{
  constructor(url){this.url=url;this.id=0;this.pending=new Map()}
  async connect(){this.ws=new WebSocket(this.url);await new Promise((resolve,reject)=>{this.ws.onopen=resolve;this.ws.onerror=reject});this.ws.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.id&&this.pending.has(msg.id)){const {resolve,reject}=this.pending.get(msg.id);this.pending.delete(msg.id);msg.error?reject(new Error(JSON.stringify(msg.error))):resolve(msg.result||{})}}}
  cmd(method,params={}){const id=++this.id;return new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params}))})}
  async eval(expression){const r=await this.cmd('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error('Browser JS: '+JSON.stringify(r.exceptionDetails));return r.result?.value}
  viewport(width,height=900){return this.cmd('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false})}
  async render(body,css,width=1440,height=900){await this.viewport(width,height);const doc='<!doctype html><html><head><meta charset="utf-8"><style>'+css+'</style></head><body><main class="wrap practice-main">'+body+'</main></body></html>';await this.eval(`document.open();document.write(${JSON.stringify(doc)});document.close();true`);await sleep(30)}
  close(){try{this.ws.close()}catch{}}
}
function section(html,klass){const re=new RegExp(`<section[^>]*class="[^"]*${klass}[^"]*"[^>]*>[\\s\\S]*?<\\/section>`);return html.match(re)?.[0]||''}
(async()=>{let chrome,cdp,tmp;try{
  const chromium=process.env.CHROMIUM_PATH||'/usr/bin/chromium';if(!fs.existsSync(chromium))throw new Error('Chromium not found at '+chromium);
  tmp=fs.mkdtempSync(path.join(os.tmpdir(),'lwu-chrome-'));
  chrome=spawn(chromium,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--remote-allow-origins=*',`--remote-debugging-port=${DEBUG}`,`--user-data-dir=${tmp}`,'about:blank'],{stdio:'ignore'});
  await waitJson(`http://127.0.0.1:${DEBUG}/json/version`);
  const target=await (await fetch(`http://127.0.0.1:${DEBUG}/json/new?about:blank`,{method:'PUT'})).json();cdp=new CDP(target.webSocketDebuggerUrl);await cdp.connect();await cdp.cmd('Page.enable');await cdp.cmd('Runtime.enable');
  const css=['learning.css','practice.css','learning-journey.css'].map(f=>fs.readFileSync(path.join(pub,'assets',f),'utf8')).join('\n');
  for(const name of ['sports.html','life-skills.html','games.html','multiplication-tables.html','planets.html','countries-capitals.html']){
    const html=fs.readFileSync(path.join(pub,'learn','kids',name),'utf8'),frag=section(html,'topic-quiz-journey');ok(!!frag,name+' has no journey section to render');if(!frag)continue;await cdp.render(frag,css);
    const d=await cdp.eval(`(()=>{const c=document.querySelector('.topic-quiz-journey'),a=[...c.querySelectorAll('.journey-actions>a,.journey-actions>button')];const rs=a.map(x=>{const r=x.getBoundingClientRect(),s=getComputedStyle(x);return{x:r.x,right:r.right,y:r.y,w:r.width,h:r.height,d:s.display}});return{count:a.length,rects:rs,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth}})()`);
    ok(d.count>=2,name+' should have at least Quiz + Next/secondary actions');ok(!d.overflow,name+' journey overflows desktop viewport');ok(d.rects.every(r=>r.d==='flex'),name+' actions are not button-like flex controls');ok(d.rects.every(r=>r.h>=54),name+' has a journey button shorter than 54px');if(d.rects.length<=3){ok(Math.max(...d.rects.map(r=>r.h))-Math.min(...d.rects.map(r=>r.h))<=2.5,name+' action heights are misaligned');ok(Math.max(...d.rects.map(r=>r.w))-Math.min(...d.rects.map(r=>r.w))<=3.5,name+' action widths are misaligned')}
  }
  const phonics='<section class="practice-box topic-quiz-journey finish-note"><p class="eyebrow">Learn → practise → quiz</p><h2>🎯 Ready for the Picture Spelling challenge?</h2><p>You finished the phonics picture words. Try the picture spelling quiz, then continue to the 100 Picture Words collection.</p><div class="journey-actions"><a class="practice-button journey-primary">Start Picture Spelling Quiz →</a><a class="practice-button journey-secondary">Next: Picture Words →</a></div></section>';
  await cdp.render(phonics,css);let d=await cdp.eval(`(()=>{const a=[...document.querySelectorAll('.journey-actions a')].map(x=>x.getBoundingClientRect());return{w:a.map(r=>r.width),h:a.map(r=>r.height),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth}})()`);ok(d.w.length===2,'Rendered Phonics journey does not have exactly Quiz + Next buttons');ok(Math.max(...d.w)-Math.min(...d.w)<=3.5,'Phonics desktop buttons are not equal width');ok(Math.max(...d.h)-Math.min(...d.h)<=2.5,'Phonics desktop buttons are not equal height');ok(!d.overflow,'Phonics desktop journey overflows');
  await cdp.render(phonics,css,390,844);d=await cdp.eval(`(()=>{const a=[...document.querySelectorAll('.journey-actions a')].map(x=>x.getBoundingClientRect());return{r:a.map(r=>({x:r.x,right:r.right,y:r.y,w:r.width,h:r.height})),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth}})()`);ok(!d.overflow,'Phonics mobile journey overflows');ok(d.r.every(r=>r.x>=-.5&&r.right<=390.5),'Phonics mobile button is clipped');ok(d.r.every((r,i)=>!i||r.y>d.r[i-1].y),'Phonics mobile buttons do not stack');
  const numberFragment='<section class="practice" id="practice"><div class="practice-heading"><div><h2>Let’s learn numbers</h2></div><span class="pill">25 numbers in this set</span></div><div class="practice-controls"><label id="numberControls">Choose a number set <select id="numberRange"><option>1–25 · Set 1</option><option>26–50 · Set 2</option><option>51–75 · Set 3</option><option>76–100 · Set 4</option></select></label></div><div class="learning-grid number-cards">'+Array.from({length:25},(_,i)=>'<article class="learning-card"><span class="card-label">Number</span><h3 class="glyph number">'+(i+1)+'</h3><p class="card-word">number</p><button class="hear-button">Hear it</button></article>').join('')+'</div><section class="practice-box topic-quiz-journey finish-note"><p class="eyebrow">Learn → practise → quiz</p><h2>🎯 Ready for the Numbers challenge?</h2><p>You explored all 25 numbers in this set.</p><div class="journey-actions"><a class="practice-button journey-primary">Start Numbers Quiz →</a><a class="practice-button journey-secondary">Next: Place Value →</a></div></section></section>';
  const numberCss=css+'\n'+fs.readFileSync(path.join(pub,'assets','kids.css'),'utf8');
  await cdp.render(numberFragment,numberCss,1440,1100);let n=await cdp.eval(`(()=>{const select=document.querySelector('#numberRange'),cards=[...document.querySelectorAll('.number-cards .learning-card')],actions=[...document.querySelectorAll('.journey-actions a')].map(x=>x.getBoundingClientRect());return{options:select.options.length,cards:cards.length,cols:getComputedStyle(document.querySelector('.number-cards')).gridTemplateColumns.split(' ').length,actionHeights:actions.map(r=>r.height),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth}})()`);ok(n.options===4,'Numbers selector does not render four options');ok(n.cards===25,'Numbers desktop view does not render 25 cards');ok(n.cols>=4,'Numbers desktop grid is too narrow');ok(Math.max(...n.actionHeights)-Math.min(...n.actionHeights)<=2.5,'Numbers journey buttons are misaligned on desktop');ok(!n.overflow,'Numbers desktop component overflows');
  await cdp.render(numberFragment,numberCss,390,1200);n=await cdp.eval(`(()=>{const select=document.querySelector('#numberRange'),cards=document.querySelectorAll('.number-cards .learning-card'),actions=[...document.querySelectorAll('.journey-actions a')].map(x=>x.getBoundingClientRect());return{options:select.options.length,cards:cards.length,actions:actions.map(r=>({x:r.x,right:r.right,y:r.y})),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth}})()`);ok(n.options===4,'Numbers mobile selector lost options');ok(n.cards===25,'Numbers mobile view does not retain all 25 cards');ok(n.actions.every(r=>r.x>=-.5&&r.right<=390.5),'Numbers mobile journey button is clipped');ok(n.actions.length===2&&n.actions[1].y>n.actions[0].y,'Numbers mobile journey buttons do not stack');ok(!n.overflow,'Numbers mobile component overflows');
  const hubHtml=fs.readFileSync(path.join(pub,'quiz','quiz-hub.html'),'utf8'),hub=section(hubHtml,'quiz-section-maths');await cdp.render(hub,css,1440,1000);let q=await cdp.eval(`(()=>{const g=document.querySelector('.quiz-grid'),c=[...g.children].slice(0,4).map(x=>x.getBoundingClientRect());return{cols:getComputedStyle(g).gridTemplateColumns.split(' ').length,h:c.map(r=>r.height),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth}})()`);ok(q.cols===4,'Quiz Hub desktop rendered grid is not four columns');ok(Math.max(...q.h)-Math.min(...q.h)<=2.5,'Quiz Hub desktop cards are not equal height');ok(!q.overflow,'Quiz Hub desktop section overflows');await cdp.render(hub,css,390,844);q=await cdp.eval(`(()=>{const g=document.querySelector('.quiz-grid');return{cols:getComputedStyle(g).gridTemplateColumns.split(' ').length,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth}})()`);ok(q.cols===1,'Quiz Hub mobile rendered grid is not one column');ok(!q.overflow,'Quiz Hub mobile section overflows');
  if(failures.length){console.error(failures.join('\n'));process.exitCode=1}else console.log(`Browser component UI checks passed: ${checks}/${checks} assertions using production HTML/CSS at desktop and mobile sizes.`)
}catch(e){console.error(e.stack||e);process.exitCode=1}finally{cdp?.close();if(chrome){chrome.kill('SIGTERM');await sleep(100)}if(tmp)fs.rmSync(tmp,{recursive:true,force:true})}})();
